export const SKILL_SUGGESTIONS = [
  'React',
  'Node.js',
  'TypeScript',
  'JavaScript',
  'UX Writing',
  'Copywriting',
  'Branding',
  'Logo Design',
  'Figma',
  'UI Design',
  'Web Design',
  'Motion Design',
  'Video Editing',
  'Social Media',
  'Google Ads',
  'Meta Ads',
  'SEO',
  'Landing Pages',
  'E-commerce',
  'Automacao',
  'Excel',
  'Power BI',
  'Traducao',
  'Atendimento',
  'Consultoria',
];
